name: barbershop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  validatorless: ^1.2.3
  iconsax: ^0.0.8
  http: ^1.2.2
  emoji_picker_flutter: ^2.1.1
  ionicons: ^0.2.2
  flutter_spinkit: ^5.2.1
  date_picker_timeline: ^1.2.6
  shared_preferences: ^2.3.1
  syncfusion_flutter_datepicker: ^26.2.9
  syncfusion_localizations: ^26.2.9
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  intl: ^0.19.0
  social_media_buttons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
    - assets/images/logo1.jpeg
    - assets/images/logo2.jpeg
    - assets/images/logo3.jpeg
    - assets/images/blank-profile.png
